const mongoose = require('mongoose');

const dailyEventDiarySchema = new mongoose.Schema({
  date: {
    type: String,
    required: true,
  },
  section: {
    type: String,
    required: true,
    enum: [
      'daily',
      'cie',
      'university-exam',
      'record-field-work',
      'transfer-knowledge-events',
      'extension-activities',
      'skill-development',
      'workshops-seminars',
      'papers-published',
      'book-chapter',
      'annual-teaching-plan',
      'mentoring',
      'patents',
      'training',
      'awards',
      'leave',
      'invited-lectures',
      'research-project',
      'database-publications',
    ],
  },
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  organizationId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Organization',
    required: true,
  },
  academicYear: { type: String, required: true, trim: true },
  entries: [{
    lectureNo: { type: String },
    class: { type: String },
    time: { type: String },
    type: { type: String },
    topic: { type: String },
    attendance: { type: String },
    details: { type: String },
    head: { type: String },
    role: { type: String },
    programName: { type: String },
    programCode: { type: String },
    title: { type: String },
    level: { type: String },
    studentsAdmitted: { type: String },
    duration: { type: String },
    theme: { type: String },
    organisedBy: { type: String },
    paperPresentation: { type: String },
    publicationDetails: { type: String },
    issn: { type: String },
    impactFactor: { type: String },
    authorType: { type: String },
    isbn: { type: String },
    publisher: { type: String },
    description: { type: String },
    mentees: { type: String },
    applicationNo: { type: String },
    publicationDate: { type: String },
    approvalDate: { type: String },
    validUpto: { type: String },
    organisedBy: { type: String },
    conferredBy: { type: String },
    dateRange: { type: String },
    date: { type: String },
    agency: { type: String },
    amountMobilized: { type: String },
    status: { type: String },
    domain: { type: String },
    pdf: { type: String },
  }],
}, { timestamps: true });

// Compound index to ensure one record per day, per user, per organization, per section
dailyEventDiarySchema.index({ date: 1, userId: 1, organizationId: 1, section: 1 }, { unique: true });

module.exports = mongoose.model('DailyEventDiary', dailyEventDiarySchema);